name = "wallust"
repo = "codeberg:explosion-mental/wallust"
version = "latest"
type = "make"
build = "make all completions man"
binary = "wallust"
description = "Generate color palettes from images"
license = "MIT"
homepage = "https://codeberg.org/explosion-mental/wallust"

[depends]
build = ["rustc", "cargo", "git", "make"]
runtime = ["imagemagick"]

[distro]
codenames = ["trixie"]
arch = "amd64"

[control]
maintainer = "Dinh Manh Dung <dungdinhmanh0209@gmail.com>"
section = "utils"
priority = "optional"
homepage = "https://codeberg.org/explosion-mental/wallust"

[install]
"target/release/wallust" = "/usr/bin/wallust"
"completions/_wallust" = "/usr/share/zsh/site-functions/_wallust"
"completions/wallust.bash" = "/usr/share/bash-completion/completions/wallust"
"completions/wallust.fish" = "/usr/share/fish/vendor_completions.d/wallust.fish"
"man/wallust.1" = "/usr/share/man/man1/wallust.1"
"man/wallust.5" = "/usr/share/man/man5/wallust.5"
"man/wallust-cs.1" = "/usr/share/man/man1/wallust-cs.1"
"man/wallust-run.1" = "/usr/share/man/man1/wallust-run.1"
"man/wallust-theme.1" = "/usr/share/man/man1/wallust-theme.1"