name = "wallust"
repo = "codeberg:explosion-mental/wallust"
version = "latest"
type = "cargo"
build = "cargo build --release"
binary = "wallust"
description = "Generate color palettes from images"
license = "MIT"
homepage = "https://codeberg.org/explosion-mental/wallust"

[depends]
build = ["rustc", "cargo", "git", "make"]
runtime = ["imagemagick"]

[distro]
codenames = ["trixie"]
arch = "amd64"

[control]
maintainer = "Dinh Manh Dung <dungdinhmanh0209@gmail.com>"
section = "utils"
priority = "optional"
homepage = "https://codeberg.org/explosion-mental/wallust"

[install]
"target/release/wallust" = "/usr/bin/wallust"